export type ToolCategory =
  | "AI & Productivity Tools"
  | "PDF Tools"
  | "Image Tools"
  | "Text Tools"
  | "Finance & Health"
  | "SEO & Utilities";

export interface Tool {
  id: string;
  name: string;
  slug: string;
  description: string;
  category: ToolCategory;
  icon: string;
  isPopular?: boolean;
  isTrending?: boolean;
}

export const tools: Tool[] = [
  // AI & Productivity Tools (6)
  {
    id: "whatsapp-chat-analyzer",
    name: "WhatsApp Chat Analyzer",
    slug: "whatsapp-chat-analyzer",
    description: "Analyze your WhatsApp chats and get deep insights instantly.",
    category: "AI & Productivity Tools",
    isPopular: true,
    isTrending: true,
    icon: "MessageSquare",
  },
  {
    id: "passport-photo-maker",
    name: "Passport Photo Maker",
    slug: "passport-photo-maker",
    description: "Create professional passport-size photos with AI background removal.",
    category: "AI & Productivity Tools",
    isPopular: true,
    isTrending: true,
    icon: "Camera",
  },
  {
    id: "resume-ats-checker",
    name: "Resume ATS Checker",
    slug: "resume-ats-checker",
    description: "Optimize your resume to pass Applicant Tracking Systems (ATS).",
    category: "AI & Productivity Tools",
    isPopular: true,
    isTrending: true,
    icon: "FileCheck",
  },
  {
    id: "vocal-remover",
    name: "Vocal Remover",
    slug: "vocal-remover",
    description: "Separate vocals from music using advanced AI technology.",
    category: "AI & Productivity Tools",
    isPopular: true,
    isTrending: true,
    icon: "Mic2",
  },
  {
    id: "bank-statement-to-excel",
    name: "Bank Statement to Excel",
    slug: "bank-statement-to-excel",
    description: "Convert PDF bank statements to editable Excel sheets accurately.",
    category: "AI & Productivity Tools",
    isPopular: true,
    isTrending: true,
    icon: "Table",
  },
  {
    id: "electricity-bill-calculator",
    name: "Electricity Bill Calculator",
    slug: "electricity-bill-calculator",
    description: "Calculate your monthly electricity bill based on units consumed.",
    category: "AI & Productivity Tools",
    isPopular: true,
    isTrending: true,
    icon: "Zap",
  },

  // PDF Tools (10)
  {
    id: "merge-pdf",
    name: "Merge PDF",
    slug: "merge-pdf",
    description: "Combine multiple PDF files into one document.",
    category: "PDF Tools",
    icon: "FilePlus",
    isPopular: true,
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    slug: "split-pdf",
    description: "Separate one PDF into multiple files.",
    category: "PDF Tools",
    icon: "Scissors",
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    slug: "compress-pdf",
    description: "Reduce PDF file size while maintaining quality.",
    category: "PDF Tools",
    icon: "FileDown",
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    slug: "pdf-to-word",
    description: "Convert PDF documents to editable Word files.",
    category: "PDF Tools",
    icon: "FileType",
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    slug: "word-to-pdf",
    description: "Convert Word documents to professional PDF files.",
    category: "PDF Tools",
    icon: "FileText",
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    slug: "pdf-to-image",
    description: "Convert PDF pages to high-quality JPG or PNG images.",
    category: "PDF Tools",
    isPopular: true,
    isTrending: true,
    icon: "FileImage",
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    slug: "image-to-pdf",
    description: "Convert images like JPG, PNG to PDF document.",
    category: "PDF Tools",
    isPopular: true,
    isTrending: true,
    icon: "FileImage",
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    slug: "rotate-pdf",
    description: "Rotate PDF pages to the correct orientation.",
    category: "PDF Tools",
    icon: "RotateCw",
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    slug: "unlock-pdf",
    description: "Remove passwords and restrictions from PDF files.",
    category: "PDF Tools",
    icon: "LockOpen",
  },
  {
    id: "pdf-sign",
    name: "Sign PDF",
    slug: "sign-pdf",
    description: "Add your signature to PDF documents.",
    category: "PDF Tools",
    icon: "PenTool",
  },

  // Image Tools (10)
  {
    id: "image-compressor",
    name: "Image Compressor",
    slug: "image-compressor",
    description: "Compress JPG, PNG, and WebP images.",
    category: "Image Tools",
    icon: "Minimize",
    isPopular: true,
    isTrending: true,
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    slug: "image-resizer",
    description: "Resize images to specific dimensions.",
    category: "Image Tools",
    icon: "Maximize",
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    slug: "image-cropper",
    description: "Crop images to remove unwanted areas.",
    category: "Image Tools",
    icon: "Crop",
  },
  {
    id: "image-converter",
    name: "Format Converter",
    slug: "image-converter",
    description: "Convert between JPG, PNG, WebP, and GIF.",
    category: "Image Tools",
    icon: "RefreshCw",
  },
  {
    id: "bg-remover",
    name: "Background Remover",
    slug: "background-remover",
    description: "Remove background from images automatically.",
    category: "Image Tools",
    icon: "Eraser",
  },
  {
    id: "image-watermark",
    name: "Watermark Adder",
    slug: "watermark-adder",
    description: "Protect your images with custom watermarks.",
    category: "Image Tools",
    icon: "Stamp",
  },
  {
    id: "image-rotator",
    name: "Image Rotator",
    slug: "image-rotator",
    description: "Rotate or flip images easily.",
    category: "Image Tools",
    icon: "RotateCw",
  },
  {
    id: "image-enhancer",
    name: "Image Enhancer",
    slug: "image-enhancer",
    description: "Improve image quality and clarity.",
    category: "Image Tools",
    icon: "Sparkles",
  },
  {
    id: "grayscale-converter",
    name: "Grayscale Converter",
    slug: "grayscale-converter",
    description: "Convert color images to black and white.",
    category: "Image Tools",
    icon: "Palette",
  },
  {
    id: "thumbnail-generator",
    name: "Thumbnail Generator",
    slug: "thumbnail-generator",
    description: "Generate thumbnails for videos or social media.",
    category: "Image Tools",
    icon: "Youtube",
  },

  // Text Tools (10)
  {
    id: "word-counter",
    name: "Word Counter",
    slug: "word-counter",
    description: "Count words, characters, and sentences in your text.",
    category: "Text Tools",
    icon: "Type",
    isPopular: true,
  },
  {
    id: "text-to-speech",
    name: "Text to Speech",
    slug: "text-to-speech",
    description: "Convert text into natural-sounding speech for free.",
    category: "Text Tools",
    isPopular: true,
    isTrending: true,
    icon: "Volume2",
  },
  {
    id: "case-converter",
    name: "Case Converter",
    slug: "case-converter",
    description: "Convert text to uppercase, lowercase, and more.",
    category: "Text Tools",
    isPopular: true,
    isTrending: true,
    icon: "CaseSensitive",
  },
  {
    id: "paraphraser",
    name: "Paraphraser",
    slug: "paraphraser",
    description: "Rewrite sentences to avoid plagiarism.",
    category: "Text Tools",
    icon: "FileEdit",
  },
  {
    id: "remove-duplicates",
    name: "Remove Duplicates",
    slug: "remove-duplicates",
    description: "Remove duplicate lines from your text.",
    category: "Text Tools",
    icon: "Rows",
  },
  {
    id: "find-replace",
    name: "Find & Replace",
    slug: "find-replace",
    description: "Quickly find and replace text strings.",
    category: "Text Tools",
    icon: "SearchCode",
  },
  {
    id: "speech-to-text",
    name: "Speech to Text",
    slug: "speech-to-text",
    description: "Transcribe spoken words into text.",
    category: "Text Tools",
    icon: "Mic",
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    slug: "slug-generator",
    description: "Convert text into SEO-friendly URL slugs.",
    category: "Text Tools",
    icon: "Link",
  },
  {
    id: "online-notepad",
    name: "Online Notepad",
    slug: "online-notepad",
    description: "Simple, browser-based notepad for quick notes.",
    category: "Text Tools",
    icon: "Notebook",
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum",
    slug: "lorem-ipsum-generator",
    description: "Generate dummy text for your designs.",
    category: "Text Tools",
    icon: "FileText",
  },

  // Finance & Health (6)
  {
    id: "emi-calculator",
    name: "EMI Calculator",
    slug: "emi-calculator",
    description: "Calculate your monthly loan payments (EMI).",
    category: "Finance & Health",
    isPopular: true,
    isTrending: true,
    icon: "Calculator",
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    slug: "percentage-calculator",
    description: "Calculate percentages and growth rates easily.",
    category: "Finance & Health",
    isPopular: true,
    isTrending: true,
    icon: "Percent",
  },
  {
    id: "discount-calculator",
    name: "Discount Calculator",
    slug: "discount-calculator",
    description: "Calculate final prices after discounts and sales.",
    category: "Finance & Health",
    isPopular: true,
    isTrending: true,
    icon: "Tag",
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    slug: "bmi-calculator",
    description: "Calculate your Body Mass Index (BMI) easily.",
    category: "Finance & Health",
    isPopular: true,
    isTrending: true,
    icon: "Activity",
  },
  {
    id: "gst-calculator",
    name: "GST Calculator",
    slug: "gst-calculator",
    description: "Calculate GST for Pakistan and other regions.",
    category: "Finance & Health",
    icon: "ReceiptText",
  },
  {
    id: "currency-converter",
    name: "Currency Converter",
    slug: "currency-converter",
    description: "Live currency conversion (PKR focused).",
    category: "Finance & Health",
    icon: "Coins",
  },

  // SEO & Utilities (6)
  {
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    slug: "meta-tag-generator",
    description: "Generate SEO-friendly meta tags for your website.",
    category: "SEO & Utilities",
    isPopular: true,
    isTrending: true,
    icon: "Tag",
  },
  {
    id: "robots-txt-generator",
    name: "Robots.txt Generator",
    slug: "robots-txt-generator",
    description: "Create a robots.txt file to guide search engine crawlers.",
    category: "SEO & Utilities",
    isPopular: true,
    isTrending: true,
    icon: "FileText",
  },
  {
    id: "xml-sitemap-generator",
    name: "XML Sitemap Generator",
    slug: "xml-sitemap-generator",
    description: "Generate an XML sitemap for search engine indexing.",
    category: "SEO & Utilities",
    isPopular: true,
    isTrending: true,
    icon: "Globe",
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    slug: "qr-code-generator",
    description: "Create custom QR codes for URLs, text, and WiFi.",
    category: "SEO & Utilities",
    isPopular: true,
    isTrending: true,
    icon: "QrCode",
  },
  {
    id: "password-generator",
    name: "Password Generator",
    slug: "password-generator",
    description: "Generate strong, secure passwords for your accounts.",
    category: "SEO & Utilities",
    isPopular: true,
    isTrending: true,
    icon: "Lock",
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    slug: "json-formatter",
    description: "Format, beautify, and minify your JSON data.",
    category: "SEO & Utilities",
    isPopular: true,
    isTrending: true,
    icon: "Braces",
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    slug: "unit-converter",
    description: "Convert between different units of length, weight, temperature, and data.",
    category: "SEO & Utilities",
    isPopular: true,
    icon: "Ruler",
  },
];

export const categories: ToolCategory[] = [
  "AI & Productivity Tools",
  "PDF Tools",
  "Image Tools",
  "Text Tools",
  "Finance & Health",
  "SEO & Utilities",
];
